# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\x12\x10serialisationLab\"\xa2\x01\n\x07Message\x12\x11\n\tPackageID\x18\x01 \x02(\x05\x12\x10\n\x08PersonID\x18\x02 \x02(\x05\x12\x0c\n\x04Name\x18\x03 \x02(\t\x12\x11\n\tInventory\x18\x04 \x03(\x05\x12\x17\n\x0f\x43urrentLocation\x18\x05 \x01(\t\x12(\n\x05\x45nemy\x18\x06 \x01(\x0b\x32\x19.serialisationLab.Message\x12\x0e\n\x06Health\x18\x07 \x01(\x02')



_MESSAGE = DESCRIPTOR.message_types_by_name['Message']
Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:serialisationLab.Message)
  })
_sym_db.RegisterMessage(Message)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGE._serialized_start=36
  _MESSAGE._serialized_end=198
# @@protoc_insertion_point(module_scope)
